name: Mina
options:
  bundleIdPrefix: com.mina
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.4"

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: "1.10.0"

targets:
  Mina:
    type: application
    platform: iOS
    sources:
      - path: Mina
        excludes:
          - Resources/.gitkeep
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGNING_ALLOWED: "NO"
        PRODUCT_BUNDLE_IDENTIFIER: com.mina.app
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Mina needs microphone access to transcribe your voice notes into journal entries."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "Mina uses speech recognition to convert your voice into text for journaling."
        INFOPLIST_KEY_NSCameraUsageDescription: "Mina needs camera access to capture photos for your journal entries."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Mina needs photo library access to attach images to your journal entries."
        SWIFT_VERSION: "5.0"
    dependencies:
      - package: ComposableArchitecture
